databases:
  - name: ticket_app
    ipAllowList: []
    databaseName: ticket_app_production
    user: ticket_app

services:
  - type: web
    name: ticket_app
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ticket_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false